APPLICATION = exercice1_lampe
BOARD ?= unwd-range-l1-r3
RIOTBASE ?= $(CURDIR)/../..

# Modules nécessaires pour l'exercice 3
USEMODULE += periph_gpio
USEMODULE += periph_gpio_irq
USEMODULE += xtimer
USEMODULE += atomic_utils

include $(RIOTBASE)/Makefile.include
