APPLICATION = exo4_morse
BOARD ?= esp32-wroom-32
RIOTBASE ?= $(CURDIR)/../../..

USEMODULE += periph_gpio
USEMODULE += periph_gpio_irq
USEMODULE += xtimer
USEMODULE += atomic_utils

include $(RIOTBASE)/Makefile.include
