APPLICATION = exercice_addresses
BOARD ?= unwd-range-l1-r3
RIOTBASE ?= $(CURDIR)/../..

# Modules nécessaires pour l'exercice 1
USEMODULE += periph_gpio
USEMODULE += periph_gpio_irq
USEMODULE += xtimer
USEMODULE += atomic_utils

include $(RIOTBASE)/Makefile.include
