APPLICATION = exercice1_lampe
BOARD ?= esp32-wroom-32
RIOTBASE ?= $(CURDIR)/../..

# Modules nécessaires pour l'exercice 1
USEMODULE += periph_gpio
USEMODULE += periph_gpio_irq
USEMODULE += xtimer
USEMODULE += atomic_utils

include $(RIOTBASE)/Makefile.include
