APPLICATION = exercice14_shell
BOARD ?= esp32-wroom-32
RIOTBASE ?= $(CURDIR)/../..

# Required modules for the shell
USEMODULE += shell
USEMODULE += xtimer
USEMODULE += pm_layered  # for reboot support

include $(RIOTBASE)/Makefile.include
