APPLICATION = exercice14_shell
BOARD ?= unwd-range-l1-r3
RIOTBASE ?= $(CURDIR)/../..

# Required modules for the shell
USEMODULE += shell
USEMODULE += xtimer
USEMODULE += pm_layered  # for reboot support

include $(RIOTBASE)/Makefile.include
