APPLICATION = gpio_timer_exercice
BOARD ?= nucleo-l152re  # ou votre carte
RIOTBASE ?= $(CURDIR)/..

# Modules nécessaires pour l'exercice 1
USEMODULE += periph_gpio
USEMODULE += periph_gpio_irq
USEMODULE += xtimer
USEMODULE += atomic_utils

include $(RIOTBASE)/Makefile.include
