APPLICATION = exo16_modbus
BOARD ?= esp32-wroom-32
RIOTBASE ?= $(CURDIR)/../../..

USEMODULE += periph_gpio
USEMODULE += periph_uart
USEMODULE += xtimer
USEMODULE += atomic_utils

include $(RIOTBASE)/Makefile.include
